// このファイルはVSCodeの拡張機能「REST Client」を使用しています

@user_id = dummy
@url = http://localhost:8787
# @url = https://backend.jmnt34deg.workers.dev

### 動作確認
GET {{url}} HTTP/1.1
content-type: application/json

### ユーザー登録
POST {{url}}/u/{{user_id}}/w/histories HTTP/1.1
content-type: application/json

{
    "value": "wrld-012-3433-11111",
    "tiele": "タイトル"
}

### ユーザー情報一覧取得
GET {{url}}/u/{{user_id}}/w/histories HTTP/1.1
content-type: application/json


//https://backend.jmnt34deg.workers.dev/u/usr_d47e61dd-04dc-4c43-bb69-15f4a147727f/w/histories
