// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewestFileName(arg1) {
  return window['go']['main']['App']['GetNewestFileName'](arg1);
}

export function LoadSetting() {
  return window['go']['main']['App']['LoadSetting']();
}

export function OpenFolderSelectWindow() {
  return window['go']['main']['App']['OpenFolderSelectWindow']();
}

export function OutputLog(arg1) {
  return window['go']['main']['App']['OutputLog'](arg1);
}

export function PostWorldID(arg1) {
  return window['go']['main']['App']['PostWorldID'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResetOffset() {
  return window['go']['main']['App']['ResetOffset']();
}

export function SetFileName(arg1) {
  return window['go']['main']['App']['SetFileName'](arg1);
}

export function WatchFile() {
  return window['go']['main']['App']['WatchFile']();
}
