// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewestFileName(arg1:string):Promise<string>;

export function LoadSetting():Promise<string>;

export function OpenFolderSelectWindow():Promise<string>;

export function OutputLog(arg1:string):Promise<void>;

export function PostWorldID(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<void>;

export function ResetOffset():Promise<void>;

export function SetFileName(arg1:string):Promise<void>;

export function WatchFile():Promise<void>;
