// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSetting() {
  return window['go']['main']['App']['LoadSetting']();
}

export function OpenFolderSelectWindow() {
  return window['go']['main']['App']['OpenFolderSelectWindow']();
}

export function OutputLog(arg1) {
  return window['go']['main']['App']['OutputLog'](arg1);
}

export function SelectLatestLogFile(arg1) {
  return window['go']['main']['App']['SelectLatestLogFile'](arg1);
}

export function SetFileName(arg1) {
  return window['go']['main']['App']['SetFileName'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}
