// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSetting():Promise<string>;

export function OpenFolderSelectWindow():Promise<string>;

export function OutputLog(arg1:string):Promise<void>;

export function SelectLatestLogFile(arg1:string):Promise<string>;

export function SetFileName(arg1:string):Promise<void>;

export function WatchFile(arg1:string):Promise<void>;
